def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "maven3"
        jdk "Oraclejdk21"
    }
    
    environment {
        SNAP_REPO = 'vprofile-snapshot'
		NEXUS_USER = 'admin'
		NEXUS_PASS = 'abcd1234'
		RELEASE_REPO = 'vprofile-release'
		CENTRAL_REPO = 'vprofile-proxy'
		NEXUSIP = '172.31.24.197'
		NEXUSPORT = '8081'
		NEXUS_GRP_REPO = 'vprofile-group'
        NEXUS_LOGIN = 'nexuslogin'
        registryCredential = 'ecr:us-east-1:awscreds'
        appRegistry = '136162657788.dkr.ecr.us-east-1.amazonaws.com/vprofile-appimage'
        vprofileRegistry = '136162657788.dkr.ecr.us-east-1.amazonaws.com'
    }

    stages {
        stage('Build'){
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
            post {
                success {
                    echo "Now Archiving."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Test'){
            steps {
                sh 'mvn -s settings.xml test'
            }

        }

        stage('Checkstyle Analysis'){
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
        }

        stage("UploadArtifact"){
            steps{
                nexusArtifactUploader(
                  nexusVersion: 'nexus3',
                  protocol: 'http',
                  nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                  groupId: 'QA',
                  version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                  repository: "${RELEASE_REPO}",
                  credentialsId: "${NEXUS_LOGIN}",
                  artifacts: [
                    [artifactId: 'vproapp',
                     classifier: '',
                     file: 'target/vprofile-v2.war',
                     type: 'war']
                  ]
                )
            }
        }

        stage("Build app image"){
            steps {
                script {
                   dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "../Docker-files/app/multistage/" ) 
            }
        }

        stage("Upload app image"){
            steps {
               script {
                  docker.withRegistry( vprofileRegistry, registryCredential ){
                    dockerImage.push("$BUILD_NUMBER")
                    dockerImage.pudh("latest")
                  }
               }
            }
        }
    }
    
}
